# Generated by Django 5.2.16 on 2026-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SUPERVISEUR', 'Superviseur terrain'), ('AGENT', 'Agent de terrain'), ('FINANCIER', 'Financier')], default='AGENT', max_length=20),
        ),
    ]
