# Generated by Django 5.0.14 on 2026-07-16 00:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_scientifique', models.CharField(blank=True, max_length=150)),
                ('croissance_rapide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Essence',
                'verbose_name_plural': 'Essences',
                'db_table': 'essences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SiteReboisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('localite', models.CharField(max_length=150)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('superficie_hectares', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='PLANIFIE', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site de reboisement',
                'verbose_name_plural': 'Sites de reboisement',
                'db_table': 'sites_reboisement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampagnePlantation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_plantation', models.DateField()),
                ('nombre_plants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_creees', to=settings.AUTH_USER_MODEL)),
                ('essence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='reforestation.essence')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='reforestation.sitereboisement')),
            ],
            options={
                'verbose_name': 'Campagne de plantation',
                'verbose_name_plural': 'Campagnes de plantation',
                'db_table': 'campagnes_plantation',
                'ordering': ['-date_plantation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviCroissance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_controle', models.DateField()),
                ('taux_survie', models.DecimalField(decimal_places=2, help_text='Pourcentage de plants ayant survécu (0 à 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nombre_plants_vivants', models.PositiveIntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='reforestation.campagneplantation')),
                ('controle_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi de croissance',
                'verbose_name_plural': 'Suivis de croissance',
                'db_table': 'suivis_croissance',
                'ordering': ['-date_controle'],
            },
        ),
        migrations.AddIndex(
            model_name='sitereboisement',
            index=models.Index(fields=['localite'], name='sites_reboi_localit_c7ccc6_idx'),
        ),
        migrations.AddIndex(
            model_name='sitereboisement',
            index=models.Index(fields=['statut'], name='sites_reboi_statut_1871f0_idx'),
        ),
        migrations.AddIndex(
            model_name='campagneplantation',
            index=models.Index(fields=['date_plantation'], name='campagnes_p_date_pl_3ff49a_idx'),
        ),
        migrations.AddIndex(
            model_name='suivicroissance',
            index=models.Index(fields=['date_controle'], name='suivis_croi_date_co_93e5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='suivicroissance',
            index=models.Index(fields=['taux_survie'], name='suivis_croi_taux_su_e0cbb6_idx'),
        ),
    ]
