# Generated by Django 5.2.16 on 2026-07-21 00:26

import apps.reforestation.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reforestation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSuivi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.reforestation.models.chemin_photo_suivi)),
                ('legende', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_prises', to=settings.AUTH_USER_MODEL)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reforestation.suivicroissance')),
            ],
            options={
                'verbose_name': 'Photo de suivi',
                'verbose_name_plural': 'Photos de suivi',
                'db_table': 'photos_suivi',
                'ordering': ['-created_at'],
            },
        ),
    ]
