# Generated by Django 5.2.16 on 2026-07-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reforestation', '0002_photosuivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicroissance',
            name='prochaine_date_controle',
            field=models.DateField(blank=True, help_text='Date prévue pour le prochain contrôle de terrain.', null=True),
        ),
    ]
