# Generated by Django 5.2.16 on 2026-07-22 22:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reforestation', '0003_suivicroissance_prochaine_date_controle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifReboisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('portee', models.CharField(choices=[('GLOBAL', 'National'), ('PROVINCE', 'Province'), ('SITE', 'Site spécifique')], default='GLOBAL', max_length=10)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('nombre_plants_cible', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('taux_survie_minimum_vise', models.DecimalField(decimal_places=2, default=70, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_debut', models.DateField()),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('ATTEINT', 'Atteint'), ('NON_ATTEINT', 'Non atteint (échéance dépassée)'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_geres', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='reforestation.sitereboisement')),
            ],
            options={
                'verbose_name': 'Objectif de reboisement',
                'verbose_name_plural': 'Objectifs de reboisement',
                'db_table': 'objectifs_reboisement',
                'ordering': ['date_echeance'],
                'indexes': [models.Index(fields=['statut'], name='objectifs_r_statut_103838_idx'), models.Index(fields=['date_echeance'], name='objectifs_r_date_ec_dc4967_idx')],
            },
        ),
    ]
