# Generated by Django 5.0.14 on 2026-07-20 22:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reforestation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_alloue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cout_reel', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('devise', models.CharField(choices=[('XAF', 'Franc CFA (XAF)'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XAF', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='reforestation.campagneplantation')),
            ],
            options={
                'verbose_name': 'Budget de campagne',
                'verbose_name_plural': 'Budgets de campagne',
                'db_table': 'budgets_campagne',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('type_partenaire', models.CharField(choices=[('ONG', 'ONG'), ('ETAT', 'État / Ministère'), ('ENTREPRISE', 'Entreprise privée'), ('BAILLEUR_INTL', 'Bailleur international'), ('AUTRE', 'Autre')], max_length=20)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_telephone', models.CharField(blank=True, max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'db_table': 'partenaires',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['type_partenaire'], name='partenaires_type_pa_0be912_idx')],
            },
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('devise', models.CharField(choices=[('XAF', 'Franc CFA (XAF)'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XAF', max_length=3)),
                ('date_financement', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Numéro de convention, référence bancaire...', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financements', to='reforestation.campagneplantation')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text="Financement global d'un site (hors campagne précise).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financements', to='reforestation.sitereboisement')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financements', to='finances.partenaire')),
            ],
            options={
                'verbose_name': 'Financement',
                'verbose_name_plural': 'Financements',
                'db_table': 'financements',
                'ordering': ['-date_financement'],
                'indexes': [models.Index(fields=['date_financement'], name='financement_date_fi_efd4c6_idx')],
            },
        ),
    ]
