# Generated by Django 5.0.14 on 2026-07-20 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('CONNEXION_ECHOUEE', 'Connexion échouée'), ('DESACTIVATION', 'Désactivation de compte')], max_length=20)),
                ('modele', models.CharField(help_text='Nom du modèle concerné (ex: SiteReboisement)', max_length=100)),
                ('objet_id', models.CharField(blank=True, max_length=100)),
                ('objet_repr', models.CharField(blank=True, help_text="Représentation lisible de l'objet", max_length=255)),
                ('details', models.JSONField(blank=True, help_text='Changements (avant/après) le cas échéant', null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'db_table': 'journal_activite',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['-date_action'], name='journal_act_date_ac_4a236b_idx'), models.Index(fields=['modele'], name='journal_act_modele_c5af2b_idx'), models.Index(fields=['action'], name='journal_act_action_4b0693_idx'), models.Index(fields=['utilisateur'], name='journal_act_utilisa_8bf92a_idx')],
            },
        ),
    ]
