# Generated by Django 5.2.16 on 2026-07-21 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('TAUX_CRITIQUE', 'Taux de survie critique'), ('SUIVI_EN_RETARD', 'Suivi en retard'), ('SUIVI_A_VENIR', 'Suivi programmé bientôt'), ('NOUVEAU_FINANCEMENT', 'Nouveau financement reçu'), ('COMPTE_CREE', 'Compte créé')], max_length=25)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('lien_objet_id', models.CharField(blank=True, max_length=100)),
                ('lien_modele', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='notificatio_destina_6faf8c_idx')],
            },
        ),
    ]
